# The base configuration of the benchmark
log: True
name: ["QIN",]
label: "_"
file_type: ".hdf5"
views:
pathf: "/home/baptiste/Documents/Datasets/QIN/"
nice: 0
random_state: 42
nb_cores: 4
full: True
debug: True
add_noise: False
noise_std: 0.0
res_dir: "../results/"
track_tracebacks: False

# All the classification-realted configuration options
multiclass_method: "oneVersusOne"
split: 0.25
nb_folds: 5
nb_class: 2
classes:
type: ["monoview"]
algos_monoview: ["decision_tree", "adaboost", "samba", "random_forest", "random_scm", "scm"]
algos_multiview:
stats_iter: 10
metrics:
  accuracy_score: {}
  f1_score: {}
metric_princ: "f1_score"
hps_type: "Random"
hps_args:
  n_iter: 20
  equivalent_draws: False